sonar.projectKey=age-check-api
sonar.projectName=age-check-api
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/.pytest_cache/**,**/Jenkinsfile,**/k8s/**,**/argocd/**

sonar.python.version=3.11
